[[jpa.repositories]]
= JPA 仓库

本章节将指出支持JPA的仓库的特性。这建立在核心仓库支持的基础上，将在“`<<仓库>>`”中进行描述。请确保您对本章节所诠释的概念有一个恰当的理解。

[[jpa.introduction]]
== 介绍

本章节描述Spring Data JPA的两种基本配置方式：

* "`<<jpa.namespace>>`" (XML 配置)
* "`<<jpa.java-config>>`" (Java 配置)

[[jpa.namespace]]
=== Spring 命名空间

Spring Data的JPA模块包含了一个用于定义仓库bean的自定义命名空间。它还提供了JPA专用的特性及组件属性。通常，JPA仓库可以用 `repositories` 组件来设置，如下例所示：

.使用命名空间来建立JPA仓库
====
[source, xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:jpa="http://www.springframework.org/schema/data/jpa"
  xsi:schemaLocation="http://www.springframework.org/schema/beans
    http://www.springframework.org/schema/beans/spring-beans.xsd
    http://www.springframework.org/schema/data/jpa
    http://www.springframework.org/schema/data/jpa/spring-jpa.xsd">

  <jpa:repositories base-package="com.acme.repositories" />

</beans>
----
====

使用 `仓库` 组件来寻找Spring Data仓库可见“`<<repositories.create-instances>>`”。另外，对以@Repository标注的bean，它激活了持久层异常的转换，使得JPA持久层提供者所抛出的异常能被转换为Spring的 `DataAccessException` 。

==== 自定义命名空间属性
除了 `repositories` 组件的默认属性，JPA命名空间提供了其他附加属性，使得你能更详细地控制仓库的设置：

.`repositories`组件的自定义属性
[options = "autowidth"]
|===============
|`entity-manager-factory-ref`|显式地与被 `repositories` 组件检测到的仓库所使用的 `EntityManagerFactory` 联结。通常在应用程序中使用多个 `EntityManagerFactory` 的情况下使用。如果没有配置该项，Spring Data将会自动在 `ApplicationContext` 中寻找名为 `entityManagerFactory` 的 `EntityManagerFactory` 类型的bean。
|`transaction-manager-ref`|显式地与被 `repositories` 组件检测到的仓库所使用的 `PlatformTransactionManager` 联结。通常只在使用了多个事务管理器或 `EntityManagerFactory` 被配置的情况下是必须的。默认为定义于当前 `ApplicationContext` 的单个 `PlatformTransactionManager`。
|===============

NOTE: Spring Data JPA需要一个名为 `transactionManager` 的 `PlatformTransactionManager` 类型的bean存在，如果没有显式地定义 `transaction-manager-ref` 的话。

[[jpa.java-config]]
=== 基于注解的配置
Spring Data JPA的仓库支持不仅可由XML命名空间激活，还可通过JavaConfig使用注解激活，如下所示：

.Spring Data JPA 仓库，使用 JavaConfig
====
[source, java]
----
@Configuration
@EnableJpaRepositories
@EnableTransactionManagement
class ApplicationConfig {

  @Bean
  public DataSource dataSource() {

    EmbeddedDatabaseBuilder builder = new EmbeddedDatabaseBuilder();
    return builder.setType(EmbeddedDatabaseType.HSQL).build();
  }

  @Bean
  public LocalContainerEntityManagerFactoryBean entityManagerFactory() {

    HibernateJpaVendorAdapter vendorAdapter = new HibernateJpaVendorAdapter();
    vendorAdapter.setGenerateDdl(true);

    LocalContainerEntityManagerFactoryBean factory = new LocalContainerEntityManagerFactoryBean();
    factory.setJpaVendorAdapter(vendorAdapter);
    factory.setPackagesToScan("com.acme.domain");
    factory.setDataSource(dataSource());
    return factory;
  }

  @Bean
  public PlatformTransactionManager transactionManager(EntityManagerFactory entityManagerFactory) {

    JpaTransactionManager txManager = new JpaTransactionManager();
    txManager.setEntityManagerFactory(entityManagerFactory);
    return txManager;
  }
}
----
====
NOTE: 你必须创建 `LocalContainerEntityManagerFactoryBean` 而不是直接创建 `EntityManagerFactory` ，因为前者在创建 `EntityManagerFactory`，还参与着异常转换机制。

上述的配置类使用了  `spring-jdbc` 的`EmbeddedDatabaseBuilder` 接口来设置了一个内嵌的HSQL数据库。之后，Spring Data设置了一个 `EntityManagerFactory` ，并使用Hibernate作为样本持久层提供者。最后一个被声明的基础组件是 `JpaTransactionManager`。总之，这个例子使用了 `@EnableJpaRepositories` 注解来激活 Spring Data JPA的仓库，其本质上和XML命名空间一样携带着相同的属性。如果没有设定一个基本的包，它将会使用这个配置类所在的包作为仓库所在的包。

[[jpa.entity-persistence]]
== 持久化实体

该部分将介绍如何用Spring Data JPA来持久化（保存）实体。

[[jpa.entity-persistence.saving-entites]]
=== 保存实体

保存实体可以用 `CrudRepository.save(…)` 方法来实现。它使用内建的JPA `EntityManager` 来持久化或合并给定的实体。如果该实体还没有被持久化，Spring Data JPA会通过调用 `entityManager.persist(...)` 方法来保存该实体。要不然，它就调用 `entityManager.merge(…)` 方法。

==== 实体状态检测策略
Spring Data JPA提供了以下策略来检测一个实体是不是新的：

* Id属性检测 (*默认*)：默认情况下Spring Data JPA检测给定实体的标识符属性。如果标识符属性为 `null` ，该实体就会被认为是新的。否则，就认为是旧的。
* 实现 `Persistable`: 如果一个实体实现了 `Persistable`, Spring Data JPA 会把新旧检测委托给实体中的 `isNew(…)` 方法。 见 link:$$http://docs.spring.io/spring-data/data-commons/docs/current/api/index.html?org/springframework/data/domain/Persistable.html$$[JavaDoc] 。
* 实现 `EntityInformation`：你可以创建 `JpaRepositoryFactory` 的子类并相应地重写 `getEntityInformation(…)` 方法来定制一个用于 `SimpleJpaRepository` 的 `EntityInformation` 的抽象实现。然后，你需要把你所自定义实现的 `JpaRepositoryFactory` 注册为一个Spring Bean。见 link:$$http://docs.spring.io/spring-data/data-jpa/docs/current/api/index.html?org/springframework/data/jpa/repository/support/JpaRepositoryFactory.html$$[JavaDoc] 。

[[jpa.query-methods]]
== 查询方法

本部分介绍Spring Data JPA中创建查询的几种方式。

[[jpa.sample-app.finders.strategies]]
=== 查询查找策略

JPA模块支持以字符串形式手工定义查询，或从方法名中推导出查询。

==== 声明查询
尽管从方法名中推导得到查询相当方便，你也很难避免这两种情况：方法名解析器不支持你想使用的关键字，或方法名不可避免地变得很丑。所以你可以使用命名约定来使用JPA命名查询（见<<jpa.query-methods.named-queries>>），或者用@Query标注你的查询方法（见<<jpa.query-methods.at-query>>）。

[[jpa.query-methods.query-creation]]
=== 创建查询

通常情况下，JPA的查询创建机制如 "`<<repositories.query-methods>>`" 所描述的一样运作。以下例子展示了一个JPA查询方法将转化为什么：

.从方法名中创建查询
====
----
public interface UserRepository extends Repository<User, Long> {

  List<User> findByEmailAddressAndLastname(String emailAddress, String lastname);
}
----
我们在这里用JPA条件(criteria)API来创建了一个查询，但本质上，这个方法转化为以下的查询语句：`select u from User u where u.emailAddress = ?1 and u.lastname = ?2`。Spring Data JPA完成了类型检查并遍历嵌套属性，如 "`<<repositories.query-methods.query-property-expressions>>`" 所描述的。
====

以下表格描述了JPA支持的关键字，以及包含着这些关键字的方法将会转化为什么：

.可用于方法名中的关键字
[options = "header, autowidth"]
|===============
|关键字|示例|JPQL 片段
|`And`|`findByLastnameAndFirstname`|`… where x.lastname = ?1 and x.firstname = ?2`
|`Or`|`findByLastnameOrFirstname`|`… where x.lastname = ?1 or x.firstname = ?2`
|`Is,Equals`|`findByFirstname`,`findByFirstnameIs`,`findByFirstnameEquals`|`… where x.firstname = ?1`
|`Between`|`findByStartDateBetween`|`… where x.startDate between ?1 and ?2`
|`LessThan`|`findByAgeLessThan`|`… where x.age < ?1`
|`LessThanEqual`|`findByAgeLessThanEqual`|`… where x.age \<= ?1`
|`GreaterThan`|`findByAgeGreaterThan`|`… where x.age > ?1`
|`GreaterThanEqual`|`findByAgeGreaterThanEqual`|`… where x.age >= ?1`
|`After`|`findByStartDateAfter`|`… where x.startDate > ?1`
|`Before`|`findByStartDateBefore`|`… where x.startDate < ?1`
|`IsNull`|`findByAgeIsNull`|`… where x.age is null`
|`IsNotNull,NotNull`|`findByAge(Is)NotNull`|`… where x.age not null`
|`Like`|`findByFirstnameLike`|`… where x.firstname like ?1`
|`NotLike`|`findByFirstnameNotLike`|`… where x.firstname not like ?1`
|`StartingWith`|`findByFirstnameStartingWith`|`… where x.firstname like ?1` (parameter bound with appended `%`)
|`EndingWith`|`findByFirstnameEndingWith`|`… where x.firstname like ?1` (parameter bound with prepended `%`)
|`Containing`|`findByFirstnameContaining`|`… where x.firstname like ?1` (parameter bound wrapped in `%`)
|`OrderBy`|`findByAgeOrderByLastnameDesc`|`… where x.age = ?1 order by x.lastname desc`
|`Not`|`findByLastnameNot`|`… where x.lastname <> ?1`
|`In`|`findByAgeIn(Collection<Age> ages)`|`… where x.age in ?1`
|`NotIn`|`findByAgeNotIn(Collection<Age> ages)`|`… where x.age not in ?1`
|`True`|`findByActiveTrue()`|`… where x.active = true`
|`False`|`findByActiveFalse()`|`… where x.active = false`
|`IgnoreCase`|`findByFirstnameIgnoreCase`|`… where UPPER(x.firstame) = UPPER(?1)`
|===============

NOTE: `In` 和 `NotIn` 也可以把 `Collection` 的子类、数组以及可变参数作为参数。关于相同逻辑运算符的不同语法版本，见 "`<<repository-query-keywords>>`" 。

[[jpa.query-methods.named-queries]]
=== 使用JPA命名查询

NOTE: 本例子使用了 `<named-query />` 和 `@NamedQuery` 注解。这些配置元素的查询必须定义在JPA查询语言中。当然，你也可以使用 `<named-native-query />` 或者 `@NamedNativeQuery`。这些元素让你能够对脱离数据库平台的依赖来在原生SQL中定义查询。

==== XML命名查询定义
要使用XML配置，必须要往JPA配置文件 `orm.xml` 添加 `<named-query />` 元素，该文件位于环境变量里的 `META-INF` 文件夹里。命名查询的自动调用需要使用一些定义好的命名约定。更多细节见下。

.XML命名查询配置
====
[source, xml]
----
<named-query name="User.findByLastname">
  <query>select u from User u where u.lastname = ?1</query>
</named-query>
----
====

这个查询有一个将在运行时解析的特定名字。

====  基于注解的配置
基于注解的配置有个好处就是不需要编辑其他的配置文件，减少维护工作量。不过，你要付出的代价就是每次有新的查询声明，你都得重新编译你的域类。

.基于注解的命名查询配置
====
[source, java]
----
@Entity
@NamedQuery(name = "User.findByEmailAddress",
  query = "select u from User u where u.emailAddress = ?1")
public class User {

}
----
====

==== 声明接口
要使这些命名查询执行，定义 `UserRepository` 如下：

.UserRepository里定义的命名查询方法
====
[source, java]
----
public interface UserRepository extends JpaRepository<User, Long> {

  List<User> findByLastname(String lastname);

  User findByEmailAddress(String emailAddress);
}
----
====

Spring Data会尝试把对这些方法的调用解析为命名查询，以配置好的域类名开始，之后跟着“.方法名”。如此，上述例子将会使用例子里定义好的命名查询，而不是尝试根据方法名创建一个新的查询。

[[jpa.query-methods.at-query]]
=== 使用 `@Query`

使用命名查询来声明对实体的查询是个相当合理的做法，在小规模的查询里也做得很好。由于查询本身是和调用它们的Java方法是绑定在一起的，你可以直接使用Spring Data JPA的 `@Query` 注解来绑定它们，而不是将它们标注在域类里。这样可以把域类从持久层特有的信息中解放出来，并把这些查询一同置于仓库接口中。

标注了@Query的查询方法优先权位于用 `@NamedQuery` 定义的查询及声明于 `orm.xml` 的命名查询之上。

以下例子展示了用 `@Query` 注解创建的查询：

. `@Query` 在查询方法上声明查询
====
[source, java]
----
public interface UserRepository extends JpaRepository<User, Long> {

  @Query("select u from User u where u.emailAddress = ?1")
  User findByEmailAddress(String emailAddress);
}
----
====

==== 使用进阶的 `LIKE` 表达式

对于 `@Query` 创建的手动定义的查询，查询执行机制允许在查询定义内部定义进阶的 `LIKE` 表达式，如下例所示：

.@Query中的进阶 `like` 表达式
====
[source, java]
----
public interface UserRepository extends JpaRepository<User, Long> {

  @Query("select u from User u where u.firstname like %?1")
  List<User> findByFirstnameEndsWith(String firstname);
}
----
====

在上例中， `LIKE` 的分隔符(`%`)会被识别，查询会被转换成一个合法的JPQL查询（移除 `%` ）。在执行查询时，调用该方法所传递的参数将会被填充到先前提到的 `LIKE` 格式里。

==== 原生查询

`@Query` 注解允许执行原生查询，只需把 `nativeQuery` 标志设为true，如下例所示：

.用@Query在查询方法上声明原生查询
====
[source, java]
----
public interface UserRepository extends JpaRepository<User, Long> {

  @Query(value = "SELECT * FROM USERS WHERE EMAIL_ADDRESS = ?1", nativeQuery = true)
  User findByEmailAddress(String emailAddress);
}
----

====

NOTE: Spring Data JPA暂不支持原生查询的动态排序，这是因为这需要去实际操作声明好的查询，而原生SQL不能很好地做到这个。然而，你可以通过指定计数查询来为原生查询分页，如下所示：

.对使用了 `@Query` 的查询方法，声明原生计数查询来完成分页
====
[source, java]
----
public interface UserRepository extends JpaRepository<User, Long> {

  @Query(value = "SELECT * FROM USERS WHERE LASTNAME = ?1",
    countQuery = "SELECT count(*) FROM USERS WHERE LASTNAME = ?1",
    nativeQuery = true)
  Page<User> findByLastname(String lastname, Pageable pageable);
}
----

====

对命名好的原生查询，一个类似的方法是在你的查询的一个副本上添加 `.count` 后缀。不过你可能就得需要注册一个结果集来映射你的计数查询了。

[[jpa.query-methods.sorting]]
=== 排序

排序可以通过提供 `PageRequest` 来完成，也可以直接使用 `Sort` 。`Sort` 对象里使用的 `Order` 对象对应的属性要和域对象里的属性一致，这意味着这些属性将会解析为查询内部所使用的属性或别名。JPQL会将这个排序解析为状态字段路径表达式。

NOTE: 使用任何不可引用的路径表达式将会导致 `异常` 。

然而，与 <<jpa.query-methods.at-query, `@Query`>> 一起使用的 `Sort` 会使你不经意地使用未进行路径检查的 `Order` 实例，该实例包含着位于 `ORDER BY` 子句内部的函数。这是可能的，因为 `Order` 会被附加到给定的查询语句上。默认情况下，Spring Data JPA拒绝任何包含函数调用的 `Order` 实例，不过你可以使用 `JpaSort.unsafe` 来添加有潜在风险的排序。

以下例子展示 `Sort` 和 `JpaSort` 的使用，包括 `JpaSort` 的不安全使用：

.使用 `Sort` 和 `JpaSort`
====
[source, java]
----
public interface UserRepository extends JpaRepository<User, Long> {

  @Query("select u from User u where u.lastname like ?1%")
  List<User> findByAndSort(String lastname, Sort sort);

  @Query("select u.id, LENGTH(u.firstname) as fn_len from User u where u.lastname like ?1%")
  List<Object[]> findByAsArrayAndSort(String lastname, Sort sort);
}

repo.findByAndSort("lannister", new Sort("firstname"));               <1>
repo.findByAndSort("stark", new Sort("LENGTH(firstname)"));           <2>
repo.findByAndSort("targaryen", JpaSort.unsafe("LENGTH(firstname)")); <3>
repo.findByAsArrayAndSort("bolton", new Sort("fn_len"));              <4>
----
<1> 合法的 `Sort` 表达式，指向域对象里的属性（firstname）。
<2> 不合法的 `Sort` ，包含了函数调用。抛异常。
<3> 合法的 `Sort`， 包含了显式声明为 _不安全_ 的 `Order`.
<4> 合法的 `Sort` 表达式，指向定义好别名的函数。
====

[[jpa.named-parameters]]
=== 为参数命名

默认情况下，Spring Data JPA使用基于位置的参数绑定，如上例所示。这让查询方法在调整参数位置的时候有那么一点容易出错。为此，你可以使用 `@Param` 注解来为这个方法的参数指定一个名字，并在查询中使用这个名字，如下例所示：

.为参数命名
====
[source, java]
----
public interface UserRepository extends JpaRepository<User, Long> {

  @Query("select u from User u where u.firstname = :firstname or u.lastname = :lastname")
  User findByLastnameOrFirstname(@Param("lastname") String lastname,
                                 @Param("firstname") String firstname);
}
----
====

NOTE: 方法里的参数会根据查询里的位置做交换。

NOTE: Spring 4完全支持了Java 8里的参数名识别功能，在使用编译标志 `-parameters` 的基础上。若你在组建（build）时添加了这个可选的调试信息，你就可以省略 `@Param` 了。

[[jpa.query.spel-expressions]]
=== 使用 SpEL 表达式

在Spring Data JPA 1.4版本发布之际，我们支持在用 `@Query` 手动定义的查询里使用受限的SpEL模板表达式。在查询执行的时候，这些表达式会由一个预定义的参数集合所赋值。Spring Data JPA支持 `entityName` 变量。它的用法是 `select x from #{#entityName} x` 。它会把与该仓库联结的域类名插入 `entityName` 。 `entityName` 会以如下方式解析：如果该域类型已经在 `@Entity` 注解里设定好了名称属性，就使用这个名称。否则，使用该域的简化类名。

以下例子展示了在一个带有查询方法和手动定义的查询的仓库接口里，在查询语句中使用 `+#{#entityName}+` 表达式的情形。

.在仓库里的查询方法使用SpEL表达式 - entityName
====
[source, java]
----
@Entity
public class User {

  @Id
  @GeneratedValue
  Long id;

  String lastname;
}

public interface UserRepository extends JpaRepository<User,Long> {

  @Query("select u from #{#entityName} u where u.lastname = ?1")
  List<User> findByLastname(String lastname);
}
----
====

用了 `+#{#entityName}+` 变量，你就不用在 `@Query` 注解里的查询语句里写实际的实体名了。

`entityName` 可由 `@Entity` 注解自定义。SpEL不支持 `orm.xml` 里的自定义。

当然，你可以直接在查询声明里用 `User`，但这可能就要你也把查询给改了。 `#entityName` 的引用带来了从 `User` 类到另一个不同的实体名的潜在映射（比如，在使用 `@Entity(name="MyUser")` 的情况下）。

在查询语句使用 `#{#entityName}` 的另一个场景是，你想定义一个通用仓库接口，用于创建与具体的域类关联的具体的仓库接口的时候。为了不在各个具体的仓库接口里重复定义相似的自定义查询，你可以在通用的仓库接口里，把实体类名表达式用于 `@Query` 注解里的查询语句，如下例所示：

.在仓库里的查询方法使用SpEL表达式 - 继承来的实体类名
====
[source, java]
----
@MappedSuperclass
public abstract class AbstractMappedType {
  …
  String attribute
}

@Entity
public class ConcreteType extends AbstractMappedType { … }

@NoRepositoryBean
public interface MappedTypeRepository<T extends AbstractMappedType>
  extends Repository<T, Long> {

  @Query("select t from #{#entityName} t where t.attribute = ?1")
  List<T> findAllByAttribute(String attribute);
}

public interface ConcreteRepository
  extends MappedTypeRepository<ConcreteType> { … }
----
====

在上例中， `MappedTypeRepository` 是一个的通用父接口，用于几种继承于 `AbstractMappedType` 的域类。这之中还定义了通用方法 `findAllByAttribute(…)` ，可用于具体仓库接口的实例中。如果你调用 `ConcreteRepository` 里的 `findByAllAttribute(…)` ，查询将变成 `select t from ConcreteType t where t.attribute = ?1` 。

[[jpa.modifying-queries]]
=== 更新查询

上面的部分都在介绍怎样声明查询来存取给定实体或实体的集合。你还可以使用 "`<<repositories.custom-implementations>>`" 所描述的工具来添加更新查询。你只需要把查询方法用 `@Modifying` 标注，然后绑定好参数，就成功创建了一个更新查询，而这个方式对所有的自定义方法都有效。见下例：

.声明更新查询
====
[source, java]
----
@Modifying
@Query("update User u set u.firstname = ?1 where u.lastname = ?2")
int setFixedFirstnameFor(String firstname, String lastname);
----
====

这样做就使得被标注方法上的查询是一个 "update" 查询，而不是 "select" 查询。在执行完更新查询后， `EntityManager` 可能含有过时的实体，我们并不自动清除它们（详见 https://docs.oracle.com/javaee/7/api/javax/persistence/EntityManager.html[JavaDoc] 中的 `EntityManager.clear()` ），因为这将会丢掉 `EntityManager` 中所有未执行也未刷新的改动，从而造成很大影响。如果你想要 `EntityManager` 自动清空，可以把 `@Modifying` 里的 `clearAutomatically` 属性设为 `true` 。

[[jpa.modifying-queries.derived-delete]]
==== 派生删除查询
Spring Data JPA也支持派生删除查询，使得你不必显式地声明JPQL查询，如下例所示：

.使用派生删除查询
====
[source, java]
----
interface UserRepository extends Repository<User, Long> {

  void deleteByRoleId(long roleId);

  @Modifying
  @Query("delete from User u where user.role.id = ?1")
  void deleteInBulkByRoleId(long roleId);
}
----
====

尽管 `deleteByRoleId(…)` 方法看起来和 `deleteInBulkByRoleId(…)` 效果一样，从它们的被执行方式上来说，这两个方法声明之间还是有很大区别。就像方法名所暗示的一样，后一个方法对数据库发出了一条JPQL查询（定义在注解里的那个）。这意味着，即使是当下已被加载的 `User` 实例，也没法触发生命周期回调。

要确保生命周期查询被触发，请使用 `deleteByRoleId(…)`，它首先执行查询，再把查询返回回来的实例一个个删除，如此，持久层提供者就能真正地调用这些实体上的 `@PreRemove` 回调。

实际上，派生删除查询是先执行查询，再对查询结果调用 `CrudRepository.delete(Iterable<User> users)` ，同时与 `CrudRepository` 里的 `delete(...)` 方法的其他实现方法保持同步的一个捷径。

[[jpa.query-hints]]
=== 使用查询提示
为了在仓库接口中声明的查询使用JPA查询提示，你可以使用 `@QueryHints` 注解。它需要一个JPA `@QueryHint` 注解所组成的数组，附带一个布尔型标志来默认禁用提示被作用于分页查询时触发的附加计数查询，如下例所示：

.在仓库方法中使用查询提示
====
[source, java]
----
public interface UserRepository extends Repository<User, Long> {

  @QueryHints(value = { @QueryHint(name = "name", value = "value")},
              forCounting = false)
  Page<User> findByLastname(String lastname, Pageable pageable);
}
----
====
上述声明将会把配置好的 `@QueryHint` 应用于实际的查询上，并避免作用于触发的用于计算总页数的计数查询上。

[[jpa.entity-graph]]
=== 配置抓取策略和图表加载

JPA 2.1 规范引入了对指定抓取策略和图表加载的支持，对此，我们的 `@EntityGraph` 注解同样予以支持，该注解允许你引用 `@NamedEntityGraph` 定义。你可以在实体上使用该注解来配置抓取策略。抓取策略（`抓取` 或 `懒加载`） 可以由 `@EntityGraph` 里的 `type` 属性加以配置。详见JPA 2.1 Spec 3.7.4。

下例显示了如何在一个实体里定义一个带命名的实体图表：

.在一个实体里定义一个带命名的实体图表
====
[source, java]
----
@Entity
@NamedEntityGraph(name = "GroupInfo.detail",
  attributeNodes = @NamedAttributeNode("members"))
public class GroupInfo {

  // default fetch mode is lazy.
  @ManyToMany
  List<GroupMember> members = new ArrayList<GroupMember>();

  …
}
----
====

下例显示了如何在仓库查询方法里引用带命名的实体图表：

.在仓库查询方法里引用带命名的实体图表
====
[source, java]
----
@Repository
public interface GroupRepository extends CrudRepository<GroupInfo, String> {

  @EntityGraph(value = "GroupInfo.detail", type = EntityGraphType.LOAD)
  GroupInfo getByGroupName(String name);

}
----
====

也可以使用 `@EntityGraph` 来定义自组织的实体图表。给定的 `attributePaths` 会被转换为对应的 `EntityGraph` 而不需显式地在域类型中添加 `@NamedEntityGraph` ，如下例：

.在仓库查询方法中使用自组织的实体图表定义
====
[source, java]
----
@Repository
public interface GroupRepository extends CrudRepository<GroupInfo, String> {

  @EntityGraph(attributePaths = { "members" })
  GroupInfo getByGroupName(String name);

}
----
====

////////////////////////////
include::{spring-data-commons-docs}/repository-projections.adoc[leveloffset=+2]
////////////////////////////

[[jpa.stored-procedures]]
== 存储过程
JPA 2.1规范引入了对使用JPA条件API来调用存储过程的支持。我们引入了 `@Procedure` 注解来在仓库方法中声明存储过程元数据。

下例显示了如何使用以下的存储过程：

.在HSQL DB里定义存储过程 `plus1inout`
====
[source, sql]
----
/;
DROP procedure IF EXISTS plus1inout
/;
CREATE procedure plus1inout (IN arg int, OUT res int)
BEGIN ATOMIC
 set res = arg + 1;
END
/;
----
====

存储过程元数据可以通过把 `NamedStoredProcedureQuery` 注解标注于实体类上来配置。

[[jpa.stored-procedure-entity-metadata]]
.定义于实体类上的存储过程元数据
====
[source, java]
----
@Entity
@NamedStoredProcedureQuery(name = "User.plus1", procedureName = "plus1inout", parameters = {
  @StoredProcedureParameter(mode = ParameterMode.IN, name = "arg", type = Integer.class),
  @StoredProcedureParameter(mode = ParameterMode.OUT, name = "res", type = Integer.class) })
public class User {}
----
====

你可以以多种方式从仓库方法中引用存储过程。要被调用的存储过程可以直接用 `value` 或 `procedureName` 属性直接定义，也可以使用 `name` 属性间接定义。如果没有配置名字，将使用仓库方法的方法名。

下例展示了如何引用一个已经显示映射好的存储过程：

[[jpa.stored-procedure-reference]]
.引用一个已经显示映射好数据库中名为“plus1inout”的存储过程
====
[source, java]
----
@Procedure("plus1inout")
Integer explicitlyNamedPlus1inout(Integer arg);
----
====

下例展示了如何使用 `procedureName` 别名来隐式地引用映射好的存储过程：

.使用 `procedureName` 别名来隐式地引用映射好的名为“plus1inout”存储过程：
====
[source, java]
----
@Procedure(procedureName = "plus1inout")
Integer plus1inout(Integer arg);
----
====

下例展示了如何引用 `EntityManager` 中已显式映射的命名好的存储过程：

.引用 `EntityManager` 中已显式映射的命名好的存储过程"User.plus1IO"
====
[source, java]
----
@Procedure(name = "User.plus1IO")
Integer entityAnnotatedCustomNamedProcedurePlus1IO(@Param("arg") Integer arg);
----
====

下例展示了如何使用方法名来引用一个 `EntityManager` 中已隐式映射的命名好的存储过程：

.使用方法名来引用一个 `EntityManager` 中已隐式映射的命名好的存储过程"User.plus1"
====
[source, java]
----
@Procedure
Integer plus1(@Param("arg") Integer arg);
----
====

[[specifications]]
== 规范式

JPA 2引入了条件API，使得你能以编程的方式来构建查询。通过编写一个 `条件` ，你定义了一个查询某个域类的where子句。退一步讲，这些查询也可以被视为以JPA条件API约束来描述的实体类的断言。

Spring Data JPA采用了Eric Evans一书 "`Domain Driven Design`" 中规范的概念，遵循相应的语法结构，提供了一个API来定义JPA条件API下的这些规范。为了支持规范式，你可以让你的仓库继承 `JpaSpecificationExecutor` 接口，如下：

[source, java]
----
public interface CustomerRepository extends CrudRepository<Customer, Long>, JpaSpecificationExecutor {
 …
}
----

这个附加的接口有许多方法来让你以多种方式执行规范式。例如， `findAll` 方法返回所有符合规范式的实体，如下例：

[source, java]
----
List<T> findAll(Specification<T> spec);
----

`规范式` 接口如下所定义：

[source, java]
----
public interface Specification<T> {
  Predicate toPredicate(Root<T> root, CriteriaQuery<?> query,
            CriteriaBuilder builder);
}
----

规范式可以方便地在实体之上构建可扩展的断言集合，并且可被组合用于 `JpaRepository` ，而不需要再为每个组合建立查询（方法），如下所示：

.Customer的规范式
====
[source, java]
----
public class CustomerSpecs {

  public static Specification<Customer> isLongTermCustomer() {
    return new Specification<Customer>() {
      public Predicate toPredicate(Root<Customer> root, CriteriaQuery<?> query,
            CriteriaBuilder builder) {

         LocalDate date = new LocalDate().minusYears(2);
         return builder.lessThan(root.get(_Customer.createdAt), date);
      }
    };
  }

  public static Specification<Customer> hasSalesOfMoreThan(MontaryAmount value) {
    return new Specification<Customer>() {
      public Predicate toPredicate(Root<T> root, CriteriaQuery<?> query,
            CriteriaBuilder builder) {

         // build query here
      }
    };
  }
}
----
====

诚然，样板的数量有待提升（最终可能在Java 8关闭的时候减少），但客户端那边变得更好了，正如你在下面会看到的。 `_Customer`类型是JPA元模型产生器（有关示例，请见 link:$$http://docs.jboss.org/hibernate/jpamodelgen/1.0/reference/en-US/html_single/#whatisit$$[Hibernate实现文档]）所产生的元模型类型。所以 `_Customer.createdAt` 表达式，将会假定 `Customer` 会有一个 `Date` 类型的 `createAt` 属性。除此之外，我们在业务需求的抽象层级上扩展了一些条件式，并创建了可执行的 `条件式` 。所以客户端可能会这样使用 `条件式` ：

.使用实例的条件式
====
[source, java]
----
List<Customer> customers = customerRepository.findAll(isLongTermCustomer());
----
====

为什么不为这样的数据操作创建查询呢？使用单个 `条件式` 不比定义普通的查询有什么好处。条件式的威力将在组合它们创造出新的 `Specification` 对象时显现出来。你可以通过我们为你提供的构建表达式的 `Specifications` helper来完成这一步：

.组合条件式
====
[source, java]
----
MonetaryAmount amount = new MonetaryAmount(200.0, Currencies.DOLLAR);
List<Customer> customers = customerRepository.findAll(
  where(isLongTermCustomer()).or(hasSalesOfMoreThan(amount)));
----

`Specifications ` 提供了一些“ `胶水代码` ”来链接和组合 `Specification` 实例。你可以创建 `Specification` 的新实现，并把它们与已有的实现组合起来，然后用这些方法扩展你的数据操作层。
====

////////////////////////////
include::{spring-data-commons-docs}/query-by-example.adoc[leveloffset=+1]
include::query-by-example.adoc[leveloffset=+1]
////////////////////////////

[[transactions]]
== 事务

默认情况下，仓库实例里的增删改查方法都是事务的。对于读操作，事务配置里的 `readOnly` 标志为 `true` 。其他属性都在 `@Transactional` 里配置，以便默认的事务配置得以生效。详见 `SimpleJpaRepository` 的JavaDoc。如果你需要对仓库中声明的某个方法轻微调整其事务配置，在你的仓库接口中重新定义它，如下：

.自定义增删该查方法的事务配置
====
[source, java]
----
public interface UserRepository extends CrudRepository<User, Long> {

  @Override
  @Transactional(timeout = 10)
  public List<User> findAll();

  // Further query method declarations
}
----
这样做使得 `findAll()` 方法有10秒的超时，并且 `readOnly` 标志失效。
====

另一种更改事务行为的方式是使用一个观察者实现类或服务实现类来引用多个仓库，其目的是为了给非基础的增删改查行为界定一个事务范围。下例显示了如何在这样一个观察者类中使用多个仓库：

.在观察者类中为多个仓库调用定义事务
====
[source, java]
----
@Service
class UserManagementImpl implements UserManagement {

  private final UserRepository userRepository;
  private final RoleRepository roleRepository;

  @Autowired
  public UserManagementImpl(UserRepository userRepository,
    RoleRepository roleRepository) {
    this.userRepository = userRepository;
    this.roleRepository = roleRepository;
  }

  @Transactional
  public void addRoleToAllUsers(String roleName) {

    Role role = roleRepository.findByName(roleName);

    for (User user : userRepository.findAll()) {
      user.addRole(role);
      userRepository.save(user);
    }
}
----
这个例子使得对 `addRoleToAllUsers(…)` 的调用运行在事务中（在一个已有的事务中，如果没有就新建一个）。这是仓库里的事务配置就会失效，因为外部的事务配置起了实际的决定作用。要注意你必须事先激活 `<tx:annotation-driven />` 或显式地使用 `@EnableTransactionManagement` 来让观察者类里的注解配置生效。这个例子假设你使用了组件扫描功能。
====

[[transactional-query-methods]]
=== 事务查询方法
为了让你的查询方法变为事务的，在你定义的仓库接口上使用 `@Transactional` ，如下例：

.在查询方法上使用@Transactional
====
[source, java]
----
@Transactional(readOnly = true)
public interface UserRepository extends JpaRepository<User, Long> {

  List<User> findByLastname(String lastname);

  @Modifying
  @Transactional
  @Query("delete from User u where u.active = false")
  void deleteInactiveUsers();
}
----
通常你想要 `readOnly` 标志设为 `true` ，因为大多数查询方法只读数据。而相反的， `deleteInactiveUsers()` 使用了 `@Modifying` 注解，并重写了事物配置。所以，这个方法跑的时候 `readOnly` 标志是为 `false` 的。
====

[NOTE]
====
你可以通过把 `readOnly` 标志设为true来为只读查询使用事务并标记这些事务为只读的。然而这样做并不保证不会触发写查询（尽管有的数据库会在只读事务中拒绝 `INSERT` 和 `UPDATE` 子句）。相反的， `readOnly` 标记只是作为一个优化底层JDBC驱动行为的提示信息而传播。此外，Spring在底层JPA提供者上做了一些优化。例如，在使用Hibernate时，当你把事务配置为 `只读` ，刷新模式会被设为 `永不` ，这会让Hibernate跳过脏数据检查（对大对象树来说是一个很大的提升）。
====

[[locking]]
== 锁
要定义锁模式，你可以在查询方法上使用 `@Lock` 注解，如下例：

.在查询方法上定义锁元数据
====
[source, java]
----
interface UserRepository extends Repository<User, Long> {

  // Plain query method
  @Lock(LockModeType.READ)
  List<User> findByLastname(String lastname);
}
----
====

这个方法定义使得被触发的查询配备上了 `LockModeType` 为 `READ` 的锁。你也可以为基础的增删改查方法定义锁，在你的仓库接口重新定义它们，并加上 `@Lock` 注解即可，如下所示：

.为基础CRUD方法定义锁元数据
====
[source, java]
----
interface UserRepository extends Repository<User, Long> {

  // Redeclaration of a CRUD method
  @Lock(LockModeType.READ);
  List<User> findAll();
}
----
====

////////////////////////////
:leveloffset: +1
include::{spring-data-commons-docs}/auditing.adoc[]
:leveloffset: -1
////////////////////////////

[[jpa.auditing]]
== JPA 审查

[[jpa.auditing.configuration]]
=== 通用审查配置

Spring Data JPA附带了实体监听器，可用于触发审查信息的捕获。首先，你需要在你的 `orm.xml` 里注册 `AuditingEntityListener` ，用于持久层里的所有实体，如下例所示：

.orm.xml审查信息
====
[source, xml]
----
<persistence-unit-metadata>
  <persistence-unit-defaults>
    <entity-listeners>
      <entity-listener class="….data.jpa.domain.support.AuditingEntityListener" />
    </entity-listeners>
  </persistence-unit-defaults>
</persistence-unit-metadata>
----
====

你也可以在类上使用 `@EntityListeners` 注解来启用 `AuditingEntityListener` ，如下：

====
[source, java]
----
@Entity
@EntityListeners(AuditingEntityListener.class)
public class MyEntity {

}
----
====

NOTE: 审查相关特性需要环境中有 `spring-aspects.jar`。

在 `orm.xml` 配好、 `spring-aspects.jar` 装好的情况下，激活审查实际上不过是在你的配置上添加Spring Data JPA的 `auditing` 命名空间，如下：

.使用XML配置激活审查
====
[source, xml]
----
<jpa:auditing auditor-aware-ref="yourAuditorAwareBean" />
----
====

在Spring Data JPA 1.5，你可以在配置类上用 `@EnableJpaAuditing` 注解来启用审查。不过你还是要修改 `orm.xml` 和在环境中安装 `spring-aspects.jar` 。下例展示了如何使用 `@EnableJpaAuditing` 注解：

.在Java配置上激活审查
====
[source, java]
----
@Configuration
@EnableJpaAuditing
class Config {

  @Bean
  public AuditorAware<AuditableUser> auditorProvider() {
    return new AuditorAwareImpl();
  }
}
----
====

如果已有一个 `AuditorAware` 类型的bean暴露给了 `ApplicationContext` ，审查架构将自动使用它，并用它决定要设在域类型上的当前用户是谁。如果你有其他AuditorAware的实现注册给了 `ApplicationContext` ，你可以通过显示地声明 `@EnableJpaAuditing` 里的 `auditorAwareRef` 属性来选择要使用哪个实现。

[[jpa.misc]]
= 其他考虑因素

[[jpa.misc.jpa-context]]
== 在自定义实现中使用 `JpaContext`

在使用多个 `EntityManager` 实例和 <<repositories.custom-implementations,自定义仓库实现>> 时，你需要在你的仓库实现类中引用正确的 `EntityManager` 。你可以通过在 `@PersistenceContext` 注解里显式为 `EntittyManager` 命名来实现这一目的，或者，如果 `EntityManager` 是 `@Autowired` 的，使用 `@Qualifier` 。

Spring Data JPA 1.9引入了一个叫 `JpaContext` 的类，用于由受管理的域类来获得 `EntityManager` ，假定这个域类在你的应用中只由一个 `EntityManager` 实例管理。下例显示了如何在自定义仓库中使用 `JpaContext` ：

.在自定义仓库中使用 `JpaContext`
====
[source, java]
----
class UserRepositoryImpl implements UserRepositoryCustom {

  private final EntityManager em;

  @Autowired
  public UserRepositoryImpl(JpaContext context) {
    this.em = context.getEntityManagerByManagedType(User.class);
  }

  …
}
----
====

这个方法的好处在于，如果域类型被指派给不同的持久化单元，仓库不需要改动去引用这个持久化单元。

[[jpa.misc.merging-persistence-units]]
== 合并持久化单元

Spring支持持有多个持久化单元。不过，有时你可能希望有模块化你的应用，但仍然确保这些模块运行在单个持久化单元里的情况。为了支持这个行为，Spring Data JPA提供了一个 `PersistenceUnitManager` 实现，来依据持久化单元的名字来自动合并它们，如下所示：

.使用 MergingPersistenceUnitmanager
====
[source, xml]
----
<bean class="….LocalContainerEntityManagerFactoryBean">
  <property name="persistenceUnitManager">
    <bean class="….MergingPersistenceUnitManager" />
  </property>
</bean>
----
====

[[jpa.misc.entity-scanning]]
=== 扫描环境中的@Entity类和JPA映射文件

普通的JPA设置要求所有注解映射的实体类列于 `orm.xml` 中。对XML映射的文件们也是一样。Spring Data JPA提供了 `ClasspathScanningPersistenceUnitPostProcessor` 来配置一个基础包，并且可以使用一个文件名映射规则。然后，它扫描这个基础包里的 `@Entity` 和 `@MappedSuperclass` 类，加载符合文件名规范的配置文件，并将它们上交给JPA配置。后处理器必须配置如下：

.使用ClasspathScanningPersistenceUnitPostProcessor
====
[source, xml]
----
<bean class="….LocalContainerEntityManagerFactoryBean">
  <property name="persistenceUnitPostProcessors">
    <list>
      <bean class="org.springframework.data.jpa.support.ClasspathScanningPersistenceUnitPostProcessor">
        <constructor-arg value="com.acme.domain" />
        <property name="mappingFileNamePattern" value="**/*Mapping.xml" />
      </bean>
    </list>
  </property>
</bean>
----
====

Spring 3.1中，包扫描可直接配置于 `LocalContainerEntityManagerFactoryBean` 来启用对实体类的环境扫描。详见 link:$$http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/orm/jpa/LocalContainerEntityManagerFactoryBean.html#setPackagesToScan(java.lang.String...)$$[JavaDoc]。

[[jpd.misc.cdi-integration]]
== CDI 集成

仓库接口的实例通常由某个容器来创建，这是Spring与Spring Data合作时最自然的选择。Spring对创建bean实例有着成熟而复杂的支持，正如 <<repositories.create-instances>> 里所记录的一样。在1.1.0版本中，Spring Data JPA带来了自定义CDI扩展，并允许在CDI环境中使用仓库抽象。该扩展是JAR的一部分。要激活它，在你的环境变量中引入Spring Data JPA JAR。

你可以为 `EntityManagerFactory` 及 `EntityManager` 实现一个CDI制造者，来建立这个框架，如下所示：

[source, java]
----
class EntityManagerFactoryProducer {

  @Produces
  @ApplicationScoped
  public EntityManagerFactory createEntityManagerFactory() {
    return Persistence.createEntityManagerFactory("my-presistence-unit");
  }

  public void close(@Disposes EntityManagerFactory entityManagerFactory) {
    entityManagerFactory.close();
  }

  @Produces
  @RequestScoped
  public EntityManager createEntityManager(EntityManagerFactory entityManagerFactory) {
    return entityManagerFactory.createEntityManager();
  }

  public void close(@Disposes EntityManager entityManager) {
    entityManager.close();
  }
}
----

必要的设置可能因JavaEE环境而异。你可能不需要做别的，只需重新把一个 `EntityManager` 定义为CDI bean，如下：

[source, java]
----
class CdiConfig {

  @Produces
  @RequestScoped
  @PersistenceContext
  public EntityManager entityManager;
}
----

在上述例子中，容器需要能够自己创建JPA `EntityManager` 。所有的配置都不过是把JPA `EntityManager` 作为一个 CDI bean重新输出罢了。

Spring Data JPA CDI 扩展将所有可用的 `EntityManager` 实例作为CDI bean获取，并在仓库类型的bean为容器所需时为仓库创建一个代理。因此，获得一个Spring Data仓库实例只需要声明一个带 `@Injected` 的属性，如下所示：

[source, java]
----
class RepositoryClient {

  @Inject
  PersonRepository repository;

  public void businessMethod() {
    List<Person> people = repository.findAll();
  }
}
----
